apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "product-portfolio-app-frontend.fullname" . }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "product-portfolio-app-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "product-portfolio-app-frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
