apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hmpps-product-portfolio-ingress
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: hmpps-product-portfolio-ingress-hmpps-product-portfolio-prod-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
spec:
  ingressClassName: default
  tls:
    - hosts:
        - hmpps-product-portfolio-prod.apps.live.cloud-platform.service.justice.gov.uk
  rules:
    - host: hmpps-product-portfolio-prod.apps.live.cloud-platform.service.justice.gov.uk
      http:
        paths:
          - path: /
            backend:
              serviceName: hmpps-product-portfolio-service
              servicePort: http
