apiVersion: v1
kind: Service
metadata:
  name: hmpps-product-portfolio-service
  labels:
    app: hmpps-product-portfolio-service
spec:
  ports:
  - port: 4567
    name: https
    targetPort: 4567
  selector:
    app: hmpps-product-portfolio
